apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: docker-build
  namespace: wso2apim
  labels:
    name: docker-build
spec:
  triggers:
    - type: GitHub
      github:
        secret: github-credentails
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/kalemakk/wso2apim.git'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'wso2/wso2am:latest'
      # env:
      #   - name: EXAMPLE
      #     value: sample-app
  output:
    to:
      kind: ImageStreamTag
      name: 'wso2am-out:latest'
      namespace: wso2apim

